# Generated by Django 5.2.4 on 2026-04-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_id', models.CharField(db_index=True, help_text='Groups composite locks; allows full/partial rollback (NO static default; must be provided)', max_length=128)),
                ('resource_type', models.CharField(choices=[('APPOINTMENT', 'Appointment'), ('STAGING_SERVER', 'Staging Server'), ('API_CREDENTIAL', 'API Credential')], db_index=True, default='APPOINTMENT', help_text='Type of locked resource (extensible)', max_length=50)),
                ('resource_id', models.IntegerField(help_text='ID of locked resource (domain-specific PK)')),
                ('resource_key', models.CharField(blank=True, db_index=True, help_text='Optional specificity key for composite locks', max_length=128, null=True)),
                ('owner_id', models.IntegerField(help_text='ID of lock owner (User PK)')),
                ('expires_at', models.DateTimeField(help_text='Lock expiration timestamp (UTC)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('released', 'Released')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'decision_slots_resourcelock',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['decision_id', 'status'], name='decision_sl_decisio_f4cb88_idx'), models.Index(fields=['resource_type', 'resource_id', 'status'], name='decision_sl_resourc_e84de1_idx'), models.Index(fields=['expires_at', 'status'], name='decision_sl_expires_1984bd_idx'), models.Index(fields=['owner_id', 'status'], name='decision_sl_owner_i_d7ab5b_idx')],
                'constraints': [models.UniqueConstraint(fields=('resource_type', 'resource_id'), name='uniq_physical_resource_lock')],
            },
        ),
    ]
