# Generated by Django 5.2.4 on 2026-01-02 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("decision_slots", "0001_initial"),
        ("human_loop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="mentor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="human_loop.mentorprofile",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="human_loop.mentorservice",
            ),
        ),
    ]
