# Generated by Django 5.2.4 on 2026-09-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_slots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resourcelock',
            name='uniq_physical_resource_lock',
        ),
        migrations.AlterField(
            model_name='resourcelock',
            name='resource_type',
            field=models.CharField(choices=[('APPOINTMENT', 'Appointment'), ('STAGING_SERVER', 'Staging Server'), ('API_CREDENTIAL', 'API Credential'), ('TIME_SLOT', 'Time Slot')], db_index=True, default='APPOINTMENT', help_text='Type of locked resource (extensible)', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='resourcelock',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('resource_type', 'resource_id'), name='uniq_active_resource_lock'),
        ),
    ]
