# Generated by Django 5.2.4 on 2026-01-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_slots', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time_slot',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='reserved_appointment',
        ),
        migrations.RemoveField(
            model_name='appointmentrequest',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='appointmentrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='mentor',
        ),
        migrations.CreateModel(
            name='ResourceLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.IntegerField(help_text='ID of locked resource (maps to Appointment PK)')),
                ('owner_id', models.IntegerField(help_text='ID of lock owner (User PK) - IntegerField for Day 1 safety')),
                ('expires_at', models.DateTimeField(help_text='Lock expiration timestamp (UTC)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('released', 'Released')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'decision_slots_resourcelock',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resource_id', 'status'], name='decision_sl_resourc_fd49f7_idx'), models.Index(fields=['expires_at'], name='decision_sl_expires_6ad6c2_idx'), models.Index(fields=['owner_id'], name='decision_sl_owner_i_2c8fb3_idx')],
            },
        ),
    ]
