# Generated by Django 5.2.4 on 2026-01-05 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decision_slots', '0004_remove_appointment_mentor_remove_appointment_service_and_more'),
        ('payments', '0003_alter_payment_appointment'),
        ('signal_delivery', '0003_alter_notification_related_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='AppointmentRequest',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
