# Generated by Django 5.2.4 on 2026-01-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_slots', '0005_delete_appointment_delete_appointmentrequest_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='resourcelock',
            name='decision_sl_resourc_fd49f7_idx',
        ),
        migrations.RemoveIndex(
            model_name='resourcelock',
            name='decision_sl_expires_6ad6c2_idx',
        ),
        migrations.RemoveIndex(
            model_name='resourcelock',
            name='decision_sl_owner_i_2c8fb3_idx',
        ),
        migrations.AddField(
            model_name='resourcelock',
            name='decision_id',
            field=models.CharField(db_index=True, default='legacy:0', help_text='Groups composite locks; allows full/partial rollback', max_length=128),
        ),
        migrations.AddField(
            model_name='resourcelock',
            name='resource_key',
            field=models.CharField(blank=True, db_index=True, help_text='Optional specificity key for composite locks', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='resourcelock',
            name='resource_type',
            field=models.CharField(choices=[('APPOINTMENT', 'Appointment'), ('STAGING_SERVER', 'Staging Server'), ('API_CREDENTIAL', 'API Credential')], db_index=True, default='APPOINTMENT', help_text='Type of locked resource (extensible)', max_length=50),
        ),
        migrations.AlterField(
            model_name='resourcelock',
            name='owner_id',
            field=models.IntegerField(help_text='ID of lock owner (User PK)'),
        ),
        migrations.AlterField(
            model_name='resourcelock',
            name='resource_id',
            field=models.IntegerField(help_text='ID of locked resource (domain-specific PK)'),
        ),
        migrations.AddIndex(
            model_name='resourcelock',
            index=models.Index(fields=['decision_id', 'status'], name='decision_sl_decisio_f4cb88_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcelock',
            index=models.Index(fields=['resource_type', 'resource_id', 'status'], name='decision_sl_resourc_e84de1_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcelock',
            index=models.Index(fields=['expires_at', 'status'], name='decision_sl_expires_1984bd_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcelock',
            index=models.Index(fields=['owner_id', 'status'], name='decision_sl_owner_i_d7ab5b_idx'),
        ),
    ]
