# Generated by Django 5.2.4 on 2026-01-05 21:14

from django.db import migrations


def backfill_decision_ids(apps, schema_editor):
    """
    Backfill decision_id for existing ResourceLock rows.
    
    Day 3 migration: Set decision_id = "legacy:{resource_id}" for backward compatibility.
    This allows existing locks to be released using the new composite lock API.
    """
    ResourceLock = apps.get_model('decision_slots', 'ResourceLock')
    
    # Only update rows where decision_id is still the default "legacy:0"
    locks_to_update = ResourceLock.objects.filter(decision_id='legacy:0')
    
    for lock in locks_to_update:
        lock.decision_id = f"legacy:{lock.resource_id}"
    
    # Bulk update for performance
    ResourceLock.objects.bulk_update(locks_to_update, ['decision_id'], batch_size=1000)


def reverse_backfill(apps, schema_editor):
    """Reverse migration: reset to default (safe no-op)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('decision_slots', '0006_remove_resourcelock_decision_sl_resourc_fd49f7_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_decision_ids, reverse_backfill),
    ]
