# Generated by Django 5.2.4 on 2026-01-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_slots', '0007_backfill_resourcelock_decision_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcelock',
            name='decision_id',
            field=models.CharField(db_index=True, help_text='Groups composite locks; allows full/partial rollback (NO static default; must be provided)', max_length=128),
        ),
    ]
