# Generated by Django 5.2.4 on 2026-01-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("decision_slots", "0008_alter_resourcelock_decision_id"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="resourcelock",
            constraint=models.UniqueConstraint(
                fields=("resource_type", "resource_id"),
                name="uniq_physical_resource_lock",
            ),
        ),
    ]
