# Generated by Django 5.2.4 on 2025-07-30 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_users', models.PositiveIntegerField(default=0, help_text='Total number of users')),
                ('active_users_today', models.PositiveIntegerField(default=0, help_text='Active users today')),
                ('active_users_week', models.PositiveIntegerField(default=0, help_text='Active users this week')),
                ('active_users_month', models.PositiveIntegerField(default=0, help_text='Active users this month')),
                ('new_users_today', models.PositiveIntegerField(default=0, help_text='New users today')),
                ('new_users_week', models.PositiveIntegerField(default=0, help_text='New users this week')),
                ('new_users_month', models.PositiveIntegerField(default=0, help_text='New users this month')),
                ('total_mentors', models.PositiveIntegerField(default=0, help_text='Total number of mentors')),
                ('active_mentors', models.PositiveIntegerField(default=0, help_text='Active mentors')),
                ('pending_mentor_applications', models.PositiveIntegerField(default=0, help_text='Pending mentor applications')),
                ('total_appointments', models.PositiveIntegerField(default=0, help_text='Total number of appointments')),
                ('appointments_today', models.PositiveIntegerField(default=0, help_text='Appointments today')),
                ('appointments_week', models.PositiveIntegerField(default=0, help_text='Appointments this week')),
                ('appointments_month', models.PositiveIntegerField(default=0, help_text='Appointments this month')),
                ('completed_appointments', models.PositiveIntegerField(default=0, help_text='Completed appointments')),
                ('cancelled_appointments', models.PositiveIntegerField(default=0, help_text='Cancelled appointments')),
                ('total_resumes', models.PositiveIntegerField(default=0, help_text='Total number of resumes')),
                ('resumes_analyzed_today', models.PositiveIntegerField(default=0, help_text='Resumes analyzed today')),
                ('resumes_analyzed_week', models.PositiveIntegerField(default=0, help_text='Resumes analyzed this week')),
                ('resumes_analyzed_month', models.PositiveIntegerField(default=0, help_text='Resumes analyzed this month')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Total revenue', max_digits=12)),
                ('revenue_today', models.DecimalField(decimal_places=2, default=0, help_text='Today\'s revenue', max_digits=12)),
                ('revenue_week', models.DecimalField(decimal_places=2, default=0, help_text='This week\'s revenue', max_digits=12)),
                ('revenue_month', models.DecimalField(decimal_places=2, default=0, help_text='This month\'s revenue', max_digits=12)),
                ('avg_response_time', models.FloatField(default=0, help_text='Average response time (ms)')),
                ('error_rate', models.FloatField(default=0, help_text='Error rate (%)')),
                ('uptime_percentage', models.FloatField(default=100, help_text='System uptime (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Stats',
                'verbose_name_plural': 'System Stats',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Export task name', max_length=200)),
                ('export_type', models.CharField(choices=[('users', 'User data'), ('mentors', 'Mentor data'), ('appointments', 'Appointment data'), ('resumes', 'Resume data'), ('notifications', 'Notification data'), ('payments', 'Payment data'), ('system_logs', 'System logs')], max_length=20)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON'), ('excel', 'Excel'), ('pdf', 'PDF')], default='csv', max_length=10)),
                ('date_from', models.DateField(blank=True, help_text='Start date', null=True)),
                ('date_to', models.DateField(blank=True, help_text='End date', null=True)),
                ('filters', models.JSONField(default=dict, help_text='Filter conditions')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, help_text='File path', max_length=500)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size (bytes)')),
                ('record_count', models.PositiveIntegerField(default=0, help_text='Record count')),
                ('error_message', models.TextField(blank=True, help_text='Error message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('user_management', 'User management'), ('mentor_management', 'Mentor management'), ('appointment_management', 'Appointment management'), ('resume_management', 'Resume management'), ('system_config', 'System configuration'), ('data_export', 'Data export'), ('notification_send', 'Send notification'), ('payment_management', 'Payment management'), ('content_moderation', 'Content moderation'), ('security_audit', 'Security audit')], max_length=50)),
                ('action_description', models.TextField(help_text='Operation description')),
                ('target_model', models.CharField(blank=True, help_text='Target model', max_length=100)),
                ('target_id', models.IntegerField(blank=True, help_text='Target object ID', null=True)),
                ('action_data', models.JSONField(default=dict, help_text='Operation data')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin_user', 'action_type'], name='adminpanel__admin_u_73c588_idx'), models.Index(fields=['created_at'], name='adminpanel__created_f95f33_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContentModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('mentor_profile', 'Mentor profile'), ('user_review', 'User review'), ('appointment_notes', 'Appointment notes'), ('resume_content', 'Resume content'), ('system_announcement', 'System announcement')], max_length=20)),
                ('content_id', models.IntegerField(help_text='Content ID')),
                ('content_preview', models.TextField(help_text='Content preview')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], default='pending', max_length=20)),
                ('flagged_reason', models.TextField(blank=True, help_text='Flagged reason')),
                ('moderation_notes', models.TextField(blank=True, help_text='Moderation notes')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_moderations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'status'], name='adminpanel__content_590708_idx'), models.Index(fields=['status', 'created_at'], name='adminpanel__status_1e3696_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Configuration key', max_length=100, unique=True)),
                ('value', models.TextField(help_text='Configuration value')),
                ('config_type', models.CharField(choices=[('general', 'General configuration'), ('email', 'Email configuration'), ('payment', 'Payment configuration'), ('notification', 'Notification configuration'), ('security', 'Security configuration'), ('feature_flags', 'Feature flags')], default='general', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Configuration description')),
                ('is_active', models.BooleanField(default=True, help_text='Is active')),
                ('is_sensitive', models.BooleanField(default=False, help_text='Is sensitive information')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['config_type', 'key'],
                'indexes': [models.Index(fields=['config_type', 'is_active'], name='adminpanel__config__baf1d3_idx')],
            },
        ),
    ]
