# Generated by Django 5.2.4 on 2025-07-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminaction',
            name='action_data',
            field=models.JSONField(default=dict, help_text='Action data'),
        ),
        migrations.AlterField(
            model_name='adminaction',
            name='action_description',
            field=models.TextField(help_text='Action description'),
        ),
        migrations.AlterField(
            model_name='systemstats',
            name='revenue_month',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Revenue this month', max_digits=12),
        ),
        migrations.AlterField(
            model_name='systemstats',
            name='revenue_today',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Revenue today', max_digits=12),
        ),
        migrations.AlterField(
            model_name='systemstats',
            name='revenue_week',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Revenue this week', max_digits=12),
        ),
        migrations.AlterField(
            model_name='systemstats',
            name='uptime_percentage',
            field=models.FloatField(default=100, help_text='System availability (%)'),
        ),
    ]
