# Generated by Django 5.2.4 on 2025-12-09 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alter_adminaction_action_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='CareerBridge', help_text='Platform name', max_length=200)),
                ('company_name', models.CharField(default='CareerBridge Inc.', help_text='Company name', max_length=200)),
                ('support_email', models.EmailField(default='support@careerbridge.com', help_text='Support email address', max_length=254)),
                ('support_phone', models.CharField(blank=True, default='', help_text='Support phone number', max_length=20)),
                ('office_address', models.TextField(blank=True, default='', help_text='Office address')),
                ('website_url', models.URLField(default='https://careerbridge.com', help_text='Website URL')),
                ('announcement_enabled', models.BooleanField(default=False, help_text='Enable system announcement')),
                ('announcement_text', models.TextField(blank=True, default='', help_text='Announcement text')),
                ('announcement_type', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', help_text='Announcement type', max_length=20)),
                ('primary_color', models.CharField(default='#2374e1', help_text='Primary color (hex)', max_length=7)),
                ('logo_url', models.URLField(blank=True, default='', help_text='Logo URL')),
                ('favicon_url', models.URLField(blank=True, default='', help_text='Favicon URL')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', help_text='Default theme', max_length=10)),
                ('linkedin_url', models.URLField(blank=True, default='', help_text='LinkedIn URL')),
                ('twitter_url', models.URLField(blank=True, default='', help_text='Twitter URL')),
                ('instagram_url', models.URLField(blank=True, default='', help_text='Instagram URL')),
                ('youtube_url', models.URLField(blank=True, default='', help_text='YouTube URL')),
                ('openai_api_key', models.CharField(blank=True, default='', help_text='OpenAI API key', max_length=255)),
                ('stripe_secret_key', models.CharField(blank=True, default='', help_text='Stripe secret key', max_length=255)),
                ('email_api_key', models.CharField(blank=True, default='', help_text='Email service API key', max_length=255)),
                ('google_oauth_key', models.CharField(blank=True, default='', help_text='Google OAuth key', max_length=255)),
                ('smtp_host', models.CharField(blank=True, default='', help_text='SMTP host', max_length=255)),
                ('smtp_port', models.IntegerField(default=587, help_text='SMTP port')),
                ('smtp_username', models.CharField(blank=True, default='', help_text='SMTP username', max_length=255)),
                ('smtp_from_name', models.CharField(default='CareerBridge', help_text='Email sender name', max_length=255)),
                ('template_footer_text', models.TextField(blank=True, default='', help_text='Email template footer text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
