# Generated by Django 5.2.4 on 2025-12-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='accent_color',
            field=models.CharField(blank=True, default='#64748b', help_text='Accent color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='contact_description',
            field=models.TextField(blank=True, default='', help_text='Contact page description'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='contact_title',
            field=models.CharField(blank=True, default='Contact Us', help_text='Contact page title', max_length=200),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='facebook_url',
            field=models.URLField(blank=True, default='', help_text='Facebook URL'),
        ),
    ]
