# Generated by Django 5.2.4 on 2025-12-28 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_content_items'),
        ('adminpanel', '0004_add_system_settings_fields'),
    ]

    operations = [
    ]
