# Generated by Django 5.2.4 on 2026-04-16 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_initial'),
        ('ats_signals', '0001_initial'),
        ('human_loop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Batch task name', max_length=100)),
                ('notification_type', models.CharField(choices=[('appointment_reminder', 'Appointment Reminder'), ('appointment_confirmed', 'Appointment Confirmed'), ('appointment_rejected', 'Appointment Rejected'), ('appointment_cancelled', 'Appointment Cancelled'), ('appointment_expired', 'Appointment Expired'), ('appointment_rescheduled', 'Appointment Rescheduled'), ('mentor_response', 'Mentor Response'), ('feedback_submitted', 'Feedback Submitted'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('system_announcement', 'System Announcement'), ('mentor_application_submitted', 'Mentor Application Submitted'), ('mentor_application_approved', 'Mentor Application Approved'), ('mentor_application_rejected', 'Mentor Application Rejected'), ('resume_uploaded', 'Resume Uploaded'), ('support_ticket_created', 'Support Ticket Created'), ('staff_appointment_cancelled', 'Staff Appointment Cancelled'), ('staff_payment_failed', 'Staff Payment Failed'), ('staff_user_feedback_submitted', 'Staff User Feedback Submitted'), ('staff_user_reported', 'Staff User Reported'), ('staff_chat_no_response', 'Staff Chat No Response'), ('staff_appointment_upcoming', 'Staff Appointment Upcoming'), ('staff_mentor_no_confirm', 'Staff Mentor No Confirm'), ('staff_mentor_no_feedback', 'Staff Mentor No Feedback'), ('staff_repeat_failure', 'Staff Repeat Failure'), ('admin_mentor_profile_updated', 'Admin Mentor Profile Updated'), ('admin_risk_alert', 'Admin Risk Alert'), ('admin_slot_conflict', 'Admin Slot Conflict'), ('admin_refund_alert', 'Admin Refund Alert'), ('admin_mentor_low_rating', 'Admin Mentor Low Rating'), ('admin_metric_anomaly', 'Admin Metric Anomaly'), ('admin_payment_success_drop', 'Admin Payment Success Drop'), ('superadmin_system_alert', 'Superadmin System Alert'), ('superadmin_security_alert', 'Superadmin Security Alert'), ('superadmin_rule_change', 'Superadmin Rule Change'), ('resume_analysis_complete', 'Resume Analysis Complete'), ('job_match_found', 'Job Match Found'), ('referral_reward', 'Referral Reward'), ('subscription_expiry', 'Subscription Expiry'), ('welcome', 'Welcome Message')], max_length=50)),
                ('target_users', models.JSONField(default=list, help_text='Target user ID list')),
                ('target_criteria', models.JSONField(default=dict, help_text='Target user filter criteria')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_count', models.PositiveIntegerField(default=0, help_text='Total count')),
                ('sent_count', models.PositiveIntegerField(default=0, help_text='Sent count')),
                ('failed_count', models.PositiveIntegerField(default=0, help_text='Failed count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(choices=[('email', 'Email Template'), ('sms', 'SMS Template'), ('push', 'Push Template'), ('in_app', 'In-App Template')], max_length=20)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=20)),
                ('recipient', models.CharField(help_text='Recipient', max_length=255)),
                ('subject', models.CharField(blank=True, help_text='Subject', max_length=200)),
                ('content', models.TextField(help_text='Delivery content')),
                ('error_message', models.TextField(blank=True, help_text='Error message')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Retry count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, help_text='Enable email notifications')),
                ('email_appointment_reminders', models.BooleanField(default=True, help_text='Appointment reminder emails')),
                ('email_mentor_responses', models.BooleanField(default=True, help_text='Mentor response emails')),
                ('email_payment_notifications', models.BooleanField(default=True, help_text='Payment notification emails')),
                ('email_system_announcements', models.BooleanField(default=True, help_text='System announcement emails')),
                ('sms_notifications', models.BooleanField(default=False, help_text='Enable SMS notifications')),
                ('sms_appointment_reminders', models.BooleanField(default=False, help_text='Appointment reminder SMS')),
                ('sms_urgent_notifications', models.BooleanField(default=True, help_text='Urgent notification SMS')),
                ('push_notifications', models.BooleanField(default=True, help_text='Enable push notifications')),
                ('push_appointment_reminders', models.BooleanField(default=True, help_text='Appointment reminder push')),
                ('push_mentor_responses', models.BooleanField(default=True, help_text='Mentor response push')),
                ('push_job_matches', models.BooleanField(default=True, help_text='Job match push')),
                ('in_app_notifications', models.BooleanField(default=True, help_text='Enable in-app notifications')),
                ('reminder_advance_hours', models.PositiveIntegerField(default=24, help_text='Appointment reminder advance hours')),
                ('quiet_hours_start', models.TimeField(default='22:00', help_text='Quiet hours start time')),
                ('quiet_hours_end', models.TimeField(default='08:00', help_text='Quiet hours end time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=100)),
                ('template_type', models.CharField(choices=[('email', 'Email Template'), ('sms', 'SMS Template'), ('push', 'Push Template'), ('in_app', 'In-App Template')], max_length=20)),
                ('notification_type', models.CharField(choices=[('appointment_reminder', 'Appointment Reminder'), ('appointment_confirmed', 'Appointment Confirmed'), ('appointment_rejected', 'Appointment Rejected'), ('appointment_cancelled', 'Appointment Cancelled'), ('appointment_expired', 'Appointment Expired'), ('appointment_rescheduled', 'Appointment Rescheduled'), ('mentor_response', 'Mentor Response'), ('feedback_submitted', 'Feedback Submitted'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('system_announcement', 'System Announcement'), ('mentor_application_submitted', 'Mentor Application Submitted'), ('mentor_application_approved', 'Mentor Application Approved'), ('mentor_application_rejected', 'Mentor Application Rejected'), ('resume_uploaded', 'Resume Uploaded'), ('support_ticket_created', 'Support Ticket Created'), ('staff_appointment_cancelled', 'Staff Appointment Cancelled'), ('staff_payment_failed', 'Staff Payment Failed'), ('staff_user_feedback_submitted', 'Staff User Feedback Submitted'), ('staff_user_reported', 'Staff User Reported'), ('staff_chat_no_response', 'Staff Chat No Response'), ('staff_appointment_upcoming', 'Staff Appointment Upcoming'), ('staff_mentor_no_confirm', 'Staff Mentor No Confirm'), ('staff_mentor_no_feedback', 'Staff Mentor No Feedback'), ('staff_repeat_failure', 'Staff Repeat Failure'), ('admin_mentor_profile_updated', 'Admin Mentor Profile Updated'), ('admin_risk_alert', 'Admin Risk Alert'), ('admin_slot_conflict', 'Admin Slot Conflict'), ('admin_refund_alert', 'Admin Refund Alert'), ('admin_mentor_low_rating', 'Admin Mentor Low Rating'), ('admin_metric_anomaly', 'Admin Metric Anomaly'), ('admin_payment_success_drop', 'Admin Payment Success Drop'), ('superadmin_system_alert', 'Superadmin System Alert'), ('superadmin_security_alert', 'Superadmin Security Alert'), ('superadmin_rule_change', 'Superadmin Rule Change'), ('resume_analysis_complete', 'Resume Analysis Complete'), ('job_match_found', 'Job Match Found'), ('referral_reward', 'Referral Reward'), ('subscription_expiry', 'Subscription Expiry'), ('welcome', 'Welcome Message')], max_length=50)),
                ('subject', models.CharField(blank=True, help_text='Email subject', max_length=200)),
                ('title_template', models.CharField(help_text='Title template', max_length=200)),
                ('message_template', models.TextField(help_text='Message template')),
                ('variables', models.JSONField(default=dict, help_text='Template variables description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['template_type', 'notification_type'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(blank=True, choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('staff', 'Staff'), ('mentor', 'Mentor'), ('student', 'Student')], help_text='Role-based target (if user is null, all users with this role see it)', max_length=20, null=True)),
                ('notification_type', models.CharField(choices=[('appointment_reminder', 'Appointment Reminder'), ('appointment_confirmed', 'Appointment Confirmed'), ('appointment_rejected', 'Appointment Rejected'), ('appointment_cancelled', 'Appointment Cancelled'), ('appointment_expired', 'Appointment Expired'), ('appointment_rescheduled', 'Appointment Rescheduled'), ('mentor_response', 'Mentor Response'), ('feedback_submitted', 'Feedback Submitted'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('system_announcement', 'System Announcement'), ('mentor_application_submitted', 'Mentor Application Submitted'), ('mentor_application_approved', 'Mentor Application Approved'), ('mentor_application_rejected', 'Mentor Application Rejected'), ('resume_uploaded', 'Resume Uploaded'), ('support_ticket_created', 'Support Ticket Created'), ('staff_appointment_cancelled', 'Staff Appointment Cancelled'), ('staff_payment_failed', 'Staff Payment Failed'), ('staff_user_feedback_submitted', 'Staff User Feedback Submitted'), ('staff_user_reported', 'Staff User Reported'), ('staff_chat_no_response', 'Staff Chat No Response'), ('staff_appointment_upcoming', 'Staff Appointment Upcoming'), ('staff_mentor_no_confirm', 'Staff Mentor No Confirm'), ('staff_mentor_no_feedback', 'Staff Mentor No Feedback'), ('staff_repeat_failure', 'Staff Repeat Failure'), ('admin_mentor_profile_updated', 'Admin Mentor Profile Updated'), ('admin_risk_alert', 'Admin Risk Alert'), ('admin_slot_conflict', 'Admin Slot Conflict'), ('admin_refund_alert', 'Admin Refund Alert'), ('admin_mentor_low_rating', 'Admin Mentor Low Rating'), ('admin_metric_anomaly', 'Admin Metric Anomaly'), ('admin_payment_success_drop', 'Admin Payment Success Drop'), ('superadmin_system_alert', 'Superadmin System Alert'), ('superadmin_security_alert', 'Superadmin Security Alert'), ('superadmin_rule_change', 'Superadmin Rule Change'), ('resume_analysis_complete', 'Resume Analysis Complete'), ('job_match_found', 'Job Match Found'), ('referral_reward', 'Referral Reward'), ('subscription_expiry', 'Subscription Expiry'), ('welcome', 'Welcome Message')], max_length=50)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification content')),
                ('is_read', models.BooleanField(default=False, help_text='Whether read')),
                ('is_sent', models.BooleanField(default=False, help_text='Whether sent')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, help_text='Sent time', null=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='Read time', null=True)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Action payload for navigation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointment')),
                ('related_mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_loop.mentorprofile')),
                ('related_resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ats_signals.resume')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
