# Generated by Django 5.2.4 on 2025-12-21 03:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MentorApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "motivation",
                    models.TextField(help_text="Why do you want to become a mentor?"),
                ),
                (
                    "relevant_experience",
                    models.TextField(help_text="Describe your relevant experience"),
                ),
                (
                    "preferred_payment_method",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe Connect"),
                            ("paypal", "PayPal"),
                            ("bank_transfer", "Bank Transfer"),
                        ],
                        default="stripe",
                        help_text="Preferred payment method",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(blank=True, help_text="Admin review notes"),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentor_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MentorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        help_text="Brief introduction about yourself", max_length=500
                    ),
                ),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(
                        default=0, help_text="Years of professional experience"
                    ),
                ),
                (
                    "current_position",
                    models.CharField(
                        help_text="Current job title and company", max_length=200
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        help_text="Primary industry (e.g., Technology, Finance)",
                        max_length=100,
                    ),
                ),
                (
                    "stripe_account_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Connect account ID for payments",
                        max_length=100,
                    ),
                ),
                (
                    "paypal_email",
                    models.EmailField(
                        blank=True,
                        help_text="PayPal email for receiving payments",
                        max_length=254,
                    ),
                ),
                (
                    "bank_account_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Bank account information for wire transfers",
                    ),
                ),
                (
                    "payouts_enabled",
                    models.BooleanField(
                        default=False, help_text="Stripe Connect payouts enabled"
                    ),
                ),
                (
                    "charges_enabled",
                    models.BooleanField(
                        default=False, help_text="Stripe Connect charges enabled"
                    ),
                ),
                (
                    "kyc_disabled_reason",
                    models.CharField(
                        blank=True,
                        help_text="If disabled, Stripe reason",
                        max_length=255,
                    ),
                ),
                (
                    "kyc_due_by",
                    models.DateTimeField(
                        blank=True, help_text="KYC requirements due by", null=True
                    ),
                ),
                (
                    "stripe_capabilities",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stripe capabilities snapshot",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(blank=True, help_text="Admin review notes"),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                (
                    "total_earnings",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total earnings from all sessions",
                        max_digits=10,
                    ),
                ),
                (
                    "total_sessions",
                    models.PositiveIntegerField(
                        default=0, help_text="Total completed sessions"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Mentor verification status"
                    ),
                ),
                (
                    "verification_badge",
                    models.CharField(
                        blank=True, help_text="Verification badge type", max_length=50
                    ),
                ),
                (
                    "specializations",
                    models.JSONField(default=list, help_text="List of specializations"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mentor_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "mentor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MentorService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("resume_review", "Resume Review"),
                            ("mock_interview", "Mock Interview"),
                            ("career_consultation", "Career Consultation"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(help_text="Service title", max_length=200)),
                ("description", models.TextField(help_text="Service description")),
                (
                    "pricing_model",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly Rate"),
                            ("fixed", "Fixed Price"),
                            ("package", "Package Deal"),
                        ],
                        default="hourly",
                        max_length=20,
                    ),
                ),
                (
                    "price_per_hour",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price per hour in USD",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "fixed_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fixed price for the service",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "package_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Package price",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "package_sessions",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of sessions in package"
                    ),
                ),
                (
                    "platform_fee_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=15.0,
                        help_text="Platform fee percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "mentor_earnings_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=85.0,
                        help_text="Mentor earnings percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=60, help_text="Session duration in minutes"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="mentors.mentorprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["mentor", "service_type"],
                "unique_together": {("mentor", "service_type")},
            },
        ),
        migrations.CreateModel(
            name="MentorSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(help_text="Scheduled session date"),
                ),
                (
                    "scheduled_time",
                    models.TimeField(help_text="Scheduled session time"),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=60, help_text="Session duration"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Confirmation"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "user_notes",
                    models.TextField(
                        blank=True, help_text="User's notes for the session"
                    ),
                ),
                (
                    "mentor_notes",
                    models.TextField(
                        blank=True, help_text="Mentor's notes for the session"
                    ),
                ),
                (
                    "session_feedback",
                    models.TextField(blank=True, help_text="Session feedback"),
                ),
                (
                    "meeting_link",
                    models.URLField(blank=True, help_text="Video meeting link"),
                ),
                (
                    "meeting_platform",
                    models.CharField(
                        blank=True,
                        help_text="Meeting platform (Zoom, Google Meet, etc.)",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="mentors.mentorprofile",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="mentors.mentorservice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booked_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_date", "-scheduled_time"],
            },
        ),
        migrations.CreateModel(
            name="MentorPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount paid by user",
                        max_digits=8,
                    ),
                ),
                (
                    "platform_fee",
                    models.DecimalField(
                        decimal_places=2, help_text="Platform fee amount", max_digits=8
                    ),
                ),
                (
                    "mentor_earnings",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount mentor receives",
                        max_digits=8,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Tax amount",
                        max_digits=8,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("bank_transfer", "Bank Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Payment processor transaction ID",
                        max_length=100,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Refund amount",
                        max_digits=8,
                    ),
                ),
                (
                    "refund_reason",
                    models.TextField(blank=True, help_text="Reason for refund"),
                ),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="mentors.mentorprofile",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentor_payments",
                        to="mentors.mentorsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MentorNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("session_booking", "Session Booking"),
                            ("session_reminder", "Session Reminder"),
                            ("session_cancellation", "Session Cancellation"),
                            ("payment_received", "Payment Received"),
                            ("review_received", "Review Received"),
                            ("application_update", "Application Update"),
                            ("system_announcement", "System Announcement"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Notification title", max_length=200),
                ),
                ("message", models.TextField(help_text="Notification message")),
                (
                    "is_read",
                    models.BooleanField(
                        default=False, help_text="Whether notification has been read"
                    ),
                ),
                (
                    "is_sent",
                    models.BooleanField(
                        default=False, help_text="Whether email notification was sent"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "related_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mentors.mentorpayment",
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="mentors.mentorprofile",
                    ),
                ),
                (
                    "related_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mentors.mentorsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MentorAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(help_text="Start time (30-minute intervals)"),
                ),
                (
                    "end_time",
                    models.TimeField(help_text="End time (30-minute intervals)"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="mentors.mentorprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["day_of_week", "start_time"],
                "unique_together": {("mentor", "day_of_week", "start_time")},
            },
        ),
        migrations.CreateModel(
            name="MentorReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        help_text="Rating from 1 to 5",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "comment",
                    models.TextField(help_text="Review comment", max_length=500),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="mentors.mentorprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentor_reviews_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="mentors.mentorsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("mentor", "user")},
            },
        ),
    ]
