# Generated by Django 5.2.4 on 2025-12-21 04:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mentors", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mentorapplication",
            options={},
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="headline",
            field=models.CharField(
                blank=True, help_text="一句话介绍，例如: 资深 Google 工程师 | 系统设计专家", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="starting_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="起步价格，由 Seed 脚本预填或后期自动更新",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="mentorapplication",
            name="motivation",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="mentorapplication",
            name="preferred_payment_method",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe Connect"),
                    ("paypal", "PayPal"),
                    ("bank_transfer", "Bank Transfer"),
                ],
                default="stripe",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mentorapplication",
            name="relevant_experience",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="mentorapplication",
            name="review_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="mentornotification",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="mentornotification",
            name="is_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="mentornotification",
            name="message",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="mentornotification",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="mentorpayment",
            name="mentor_earnings",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="mentorpayment",
            name="platform_fee",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="mentorpayment",
            name="refund_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="mentorpayment",
            name="refund_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="mentorpayment",
            name="tax_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="mentorpayment",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="mentorpayment",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="mentorreview",
            name="comment",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="mentorreview",
            name="rating",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="mentorservice",
            name="duration_minutes",
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name="mentorservice",
            name="fixed_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mentorservice",
            name="mentor_earnings_percentage",
            field=models.DecimalField(decimal_places=2, default=85.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="mentorservice",
            name="package_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mentorservice",
            name="package_sessions",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="mentorservice",
            name="platform_fee_percentage",
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="mentorservice",
            name="price_per_hour",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mentorsession",
            name="duration_minutes",
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name="mentorsession",
            name="meeting_link",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="mentorsession",
            name="meeting_platform",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="mentorsession",
            name="mentor_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="mentorsession",
            name="session_feedback",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="mentorsession",
            name="user_notes",
            field=models.TextField(blank=True),
        ),
    ]
