# Generated by Django 5.2.4 on 2025-08-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='charges_enabled',
            field=models.BooleanField(default=False, help_text='Stripe Connect charges enabled'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='kyc_disabled_reason',
            field=models.CharField(blank=True, help_text='If disabled, Stripe reason', max_length=255),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='kyc_due_by',
            field=models.DateTimeField(blank=True, help_text='KYC requirements due by', null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='payouts_enabled',
            field=models.BooleanField(default=False, help_text='Stripe Connect payouts enabled'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='stripe_capabilities',
            field=models.JSONField(blank=True, default=dict, help_text='Stripe capabilities snapshot'),
        ),
    ]
