# Generated by Django 5.2.4 on 2025-12-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mentors", "0002_alter_mentorapplication_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorservice",
            name="deliverables",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of items delivered in this service",
            ),
        ),
    ]
