# Generated by Django 5.2.4 on 2025-12-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mentors", "0003_mentorservice_deliverables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentorprofile",
            name="headline",
            field=models.CharField(
                blank=True, help_text="A short headline", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="mentorprofile",
            name="starting_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Starting price, pre-filled or auto-updated by Seed script",
                max_digits=10,
            ),
        ),
    ]
