# Generated by Django 5.2.4 on 2025-12-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mentors", "0004_alter_mentorprofile_headline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorprofile",
            name="primary_focus",
            field=models.CharField(
                blank=True,
                help_text="Primary problem this mentor helps with (shown on mentor cards)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="session_focus",
            field=models.CharField(
                blank=True,
                help_text="One-line session experience summary (shown on mentor cards)",
                max_length=150,
            ),
        ),
    ]
