# Generated by Django 5.2.4 on 2025-12-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mentors", "0006_mentorprofile_primary_track_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentorprofile",
            name="primary_track",
            field=models.CharField(
                blank=True,
                choices=[
                    ("resume_review", "Resume Review"),
                    ("mock_interview", "Mock Interview"),
                    ("career_switch", "Career Switch"),
                    ("advanced_interview", "Advanced Interview"),
                ],
                default="",
                help_text="Primary product track this mentor belongs to",
                max_length=50,
            ),
        ),
    ]
