# Generated by Django 5.2.4 on 2025-12-22 04:47
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0007_alter_mentorprofile_primary_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='system_role',
            field=models.CharField(
                max_length=100,
                blank=True,
                help_text='System-level role, e.g. Senior System Design Reviewer',
            ),
        ),
    ]