# Generated by Django 5.2.4 on 2025-12-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0008_add_system_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='primary_service_id',
            field=models.IntegerField(blank=True, help_text='Mentor-selected primary service (SKU anchor)', null=True),
        ),
    ]
