# Generated by Django 5.2.4 on 2026-01-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("user_management", "User management"),
                            ("mentor_management", "Mentor management"),
                            ("appointment_management", "Appointment management"),
                            ("resume_management", "Resume management"),
                            ("system_config", "System configuration"),
                            ("data_export", "Data export"),
                            ("notification_send", "Send notification"),
                            ("payment_management", "Payment management"),
                            ("content_moderation", "Content moderation"),
                            ("security_audit", "Security audit"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "action_description",
                    models.TextField(help_text="Action description"),
                ),
                (
                    "target_model",
                    models.CharField(
                        blank=True, help_text="Target model", max_length=100
                    ),
                ),
                (
                    "target_id",
                    models.IntegerField(
                        blank=True, help_text="Target object ID", null=True
                    ),
                ),
                (
                    "action_data",
                    models.JSONField(default=dict, help_text="Action data"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address", null=True
                    ),
                ),
                ("user_agent", models.TextField(blank=True, help_text="User agent")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True)),
                ("body", models.TextField(blank=True)),
                ("cover_image_url", models.URLField(blank=True, default="")),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("blog", "Blog"),
                            ("resource", "Resource"),
                            ("guide", "Guide"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("published", "Published"),
                            ("draft", "Draft"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("views", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentModeration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("mentor_profile", "Mentor profile"),
                            ("user_review", "User review"),
                            ("appointment_notes", "Appointment notes"),
                            ("resume_content", "Resume content"),
                            ("system_announcement", "System announcement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content_id", models.IntegerField(help_text="Content ID")),
                ("content_preview", models.TextField(help_text="Content preview")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("flagged", "Flagged"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "flagged_reason",
                    models.TextField(blank=True, help_text="Flagged reason"),
                ),
                (
                    "moderation_notes",
                    models.TextField(blank=True, help_text="Moderation notes"),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Export task name", max_length=200),
                ),
                (
                    "export_type",
                    models.CharField(
                        choices=[
                            ("users", "User data"),
                            ("mentors", "Mentor data"),
                            ("appointments", "Appointment data"),
                            ("resumes", "Resume data"),
                            ("notifications", "Notification data"),
                            ("payments", "Payment data"),
                            ("system_logs", "System logs"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("csv", "CSV"),
                            ("json", "JSON"),
                            ("excel", "Excel"),
                            ("pdf", "PDF"),
                        ],
                        default="csv",
                        max_length=10,
                    ),
                ),
                (
                    "date_from",
                    models.DateField(blank=True, help_text="Start date", null=True),
                ),
                (
                    "date_to",
                    models.DateField(blank=True, help_text="End date", null=True),
                ),
                (
                    "filters",
                    models.JSONField(default=dict, help_text="Filter conditions"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(blank=True, help_text="File path", max_length=500),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, help_text="File size (bytes)"
                    ),
                ),
                (
                    "record_count",
                    models.PositiveIntegerField(default=0, help_text="Record count"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error message"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("staff_notes", models.TextField(blank=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Configuration key", max_length=100, unique=True
                    ),
                ),
                ("value", models.TextField(help_text="Configuration value")),
                (
                    "config_type",
                    models.CharField(
                        choices=[
                            ("general", "General configuration"),
                            ("email", "Email configuration"),
                            ("payment", "Payment configuration"),
                            ("notification", "Notification configuration"),
                            ("security", "Security configuration"),
                            ("feature_flags", "Feature flags"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Configuration description"),
                ),
                ("is_active", models.BooleanField(default=True, help_text="Is active")),
                (
                    "is_sensitive",
                    models.BooleanField(
                        default=False, help_text="Is sensitive information"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["config_type", "key"],
            },
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform_name",
                    models.CharField(
                        default="CareerBridge",
                        help_text="Platform name",
                        max_length=200,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        default="CareerBridge Inc.",
                        help_text="Company name",
                        max_length=200,
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(
                        default="support@careerbridge.com",
                        help_text="Support email address",
                        max_length=254,
                    ),
                ),
                (
                    "support_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Support phone number",
                        max_length=20,
                    ),
                ),
                (
                    "office_address",
                    models.TextField(
                        blank=True, default="", help_text="Office address"
                    ),
                ),
                (
                    "website_url",
                    models.URLField(
                        default="https://careerbridge.com", help_text="Website URL"
                    ),
                ),
                (
                    "announcement_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable system announcement"
                    ),
                ),
                (
                    "announcement_text",
                    models.TextField(
                        blank=True, default="", help_text="Announcement text"
                    ),
                ),
                (
                    "announcement_type",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("success", "Success"),
                        ],
                        default="info",
                        help_text="Announcement type",
                        max_length=20,
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#2374e1", help_text="Primary color (hex)", max_length=7
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        blank=True,
                        default="#64748b",
                        help_text="Accent color (hex)",
                        max_length=7,
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(blank=True, default="", help_text="Logo URL"),
                ),
                (
                    "favicon_url",
                    models.URLField(blank=True, default="", help_text="Favicon URL"),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("auto", "Auto"),
                        ],
                        default="light",
                        help_text="Default theme",
                        max_length=10,
                    ),
                ),
                (
                    "contact_title",
                    models.CharField(
                        blank=True,
                        default="Contact Us",
                        help_text="Contact page title",
                        max_length=200,
                    ),
                ),
                (
                    "contact_description",
                    models.TextField(
                        blank=True, default="", help_text="Contact page description"
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, default="", help_text="LinkedIn URL"),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, default="", help_text="Twitter URL"),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, default="", help_text="Instagram URL"),
                ),
                (
                    "youtube_url",
                    models.URLField(blank=True, default="", help_text="YouTube URL"),
                ),
                (
                    "facebook_url",
                    models.URLField(blank=True, default="", help_text="Facebook URL"),
                ),
                (
                    "openai_api_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="OpenAI API key",
                        max_length=255,
                    ),
                ),
                (
                    "stripe_secret_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Stripe secret key",
                        max_length=255,
                    ),
                ),
                (
                    "email_api_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Email service API key",
                        max_length=255,
                    ),
                ),
                (
                    "google_oauth_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Google OAuth key",
                        max_length=255,
                    ),
                ),
                (
                    "smtp_host",
                    models.CharField(
                        blank=True, default="", help_text="SMTP host", max_length=255
                    ),
                ),
                ("smtp_port", models.IntegerField(default=587, help_text="SMTP port")),
                (
                    "smtp_username",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SMTP username",
                        max_length=255,
                    ),
                ),
                (
                    "smtp_from_name",
                    models.CharField(
                        default="CareerBridge",
                        help_text="Email sender name",
                        max_length=255,
                    ),
                ),
                (
                    "template_footer_text",
                    models.TextField(
                        blank=True, default="", help_text="Email template footer text"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
            },
        ),
        migrations.CreateModel(
            name="SystemStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_users",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of users"
                    ),
                ),
                (
                    "active_users_today",
                    models.PositiveIntegerField(
                        default=0, help_text="Active users today"
                    ),
                ),
                (
                    "active_users_week",
                    models.PositiveIntegerField(
                        default=0, help_text="Active users this week"
                    ),
                ),
                (
                    "active_users_month",
                    models.PositiveIntegerField(
                        default=0, help_text="Active users this month"
                    ),
                ),
                (
                    "new_users_today",
                    models.PositiveIntegerField(default=0, help_text="New users today"),
                ),
                (
                    "new_users_week",
                    models.PositiveIntegerField(
                        default=0, help_text="New users this week"
                    ),
                ),
                (
                    "new_users_month",
                    models.PositiveIntegerField(
                        default=0, help_text="New users this month"
                    ),
                ),
                (
                    "total_mentors",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of mentors"
                    ),
                ),
                (
                    "active_mentors",
                    models.PositiveIntegerField(default=0, help_text="Active mentors"),
                ),
                (
                    "pending_mentor_applications",
                    models.PositiveIntegerField(
                        default=0, help_text="Pending mentor applications"
                    ),
                ),
                (
                    "total_appointments",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of appointments"
                    ),
                ),
                (
                    "appointments_today",
                    models.PositiveIntegerField(
                        default=0, help_text="Appointments today"
                    ),
                ),
                (
                    "appointments_week",
                    models.PositiveIntegerField(
                        default=0, help_text="Appointments this week"
                    ),
                ),
                (
                    "appointments_month",
                    models.PositiveIntegerField(
                        default=0, help_text="Appointments this month"
                    ),
                ),
                (
                    "completed_appointments",
                    models.PositiveIntegerField(
                        default=0, help_text="Completed appointments"
                    ),
                ),
                (
                    "cancelled_appointments",
                    models.PositiveIntegerField(
                        default=0, help_text="Cancelled appointments"
                    ),
                ),
                (
                    "total_resumes",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of resumes"
                    ),
                ),
                (
                    "resumes_analyzed_today",
                    models.PositiveIntegerField(
                        default=0, help_text="Resumes analyzed today"
                    ),
                ),
                (
                    "resumes_analyzed_week",
                    models.PositiveIntegerField(
                        default=0, help_text="Resumes analyzed this week"
                    ),
                ),
                (
                    "resumes_analyzed_month",
                    models.PositiveIntegerField(
                        default=0, help_text="Resumes analyzed this month"
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total revenue",
                        max_digits=12,
                    ),
                ),
                (
                    "revenue_today",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Revenue today",
                        max_digits=12,
                    ),
                ),
                (
                    "revenue_week",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Revenue this week",
                        max_digits=12,
                    ),
                ),
                (
                    "revenue_month",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Revenue this month",
                        max_digits=12,
                    ),
                ),
                (
                    "avg_response_time",
                    models.FloatField(
                        default=0, help_text="Average response time (ms)"
                    ),
                ),
                (
                    "error_rate",
                    models.FloatField(default=0, help_text="Error rate (%)"),
                ),
                (
                    "uptime_percentage",
                    models.FloatField(default=100, help_text="System availability (%)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Stats",
                "verbose_name_plural": "System Stats",
                "ordering": ["-created_at"],
            },
        ),
    ]
