# Generated by Django 5.2.4 on 2026-01-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaction',
            name='world',
            field=models.CharField(blank=True, default='admin', help_text='OS world: public, app, admin, or kernel', max_length=20),
        ),
    ]
