# Generated by Django 5.2.4 on 2026-01-02 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ats_signals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="datadeletionrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="dataexportjob",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="invitationcode",
            name="invitee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invitationcode",
            name="inviter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="jobdescription",
            index=models.Index(
                fields=["title", "company"], name="ats_signals_title_113ea9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobdescription",
            index=models.Index(
                fields=["source", "is_processed"], name="ats_signals_source_68dc93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobdescription",
            index=models.Index(
                fields=["external_id", "api_source"],
                name="ats_signals_externa_c89e13_idx",
            ),
        ),
        migrations.AddField(
            model_name="keywordmatch",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resumes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="keywordmatch",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keyword_matches",
                to="ats_signals.resume",
            ),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="resume",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis",
                to="ats_signals.resume",
            ),
        ),
        migrations.AddField(
            model_name="resumecomparison",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resume_comparisons",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resumecomparisonitem",
            name="comparison",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ats_signals.resumecomparison",
            ),
        ),
        migrations.AddField(
            model_name="resumecomparisonitem",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ats_signals.resume"
            ),
        ),
        migrations.AddField(
            model_name="resumecomparison",
            name="resumes",
            field=models.ManyToManyField(
                related_name="comparisons",
                through="ats_signals.ResumeComparisonItem",
                to="ats_signals.resume",
            ),
        ),
        migrations.AddField(
            model_name="resumeexport",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exports",
                to="ats_signals.resume",
            ),
        ),
        migrations.AddField(
            model_name="resumeexport",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resume_exports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resumefeedback",
            name="analysis",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="ats_signals.resumeanalysis",
            ),
        ),
        migrations.AddField(
            model_name="resumejobmatch",
            name="job_description",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resume_matches",
                to="ats_signals.jobdescription",
            ),
        ),
        migrations.AddField(
            model_name="resumejobmatch",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_matches",
                to="ats_signals.resume",
            ),
        ),
        migrations.AddField(
            model_name="resumeexport",
            name="template_used",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ats_signals.resumetemplate",
            ),
        ),
        migrations.AddField(
            model_name="serviceusagelog",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ats_signals.externalserviceintegration",
            ),
        ),
        migrations.AddField(
            model_name="serviceusagelog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userdataconsent",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_consents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userdatadeletionrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deletion_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userdisclaimerconsent",
            name="disclaimer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ats_signals.legaldisclaimer",
            ),
        ),
        migrations.AddField(
            model_name="userdisclaimerconsent",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disclaimer_consents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userreferralstats",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="resumecomparisonitem",
            unique_together={("comparison", "resume")},
        ),
        migrations.AddIndex(
            model_name="resumejobmatch",
            index=models.Index(
                fields=["overall_match_score"], name="ats_signals_overall_7309f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resumejobmatch",
            index=models.Index(
                fields=["match_level"], name="ats_signals_match_l_eefd7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resumejobmatch",
            index=models.Index(
                fields=["feedback_rating"], name="ats_signals_feedbac_e4576a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="resumejobmatch",
            unique_together={("resume", "job_description")},
        ),
        migrations.AddIndex(
            model_name="serviceusagelog",
            index=models.Index(
                fields=["service", "timestamp"], name="ats_signals_service_a371e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serviceusagelog",
            index=models.Index(
                fields=["user", "timestamp"], name="ats_signals_user_id_eabfe9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userdataconsent",
            unique_together={("user", "consent_type")},
        ),
        migrations.AlterUniqueTogether(
            name="userdisclaimerconsent",
            unique_together={("user", "disclaimer")},
        ),
    ]
