# Generated by Django 5.2.4 on 2026-01-02 03:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HumanReviewTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision_slot_id",
                    models.CharField(
                        db_index=True,
                        help_text="DecisionSlot ID anchoring this review task (Rule 15)",
                        max_length=100,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        default="signal_review",
                        help_text="Type of review task",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("assigned", "Assigned to Reviewer"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current status of the review task",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="high",
                        help_text="Priority level of the review task",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        blank=True, help_text="When task was assigned", null=True
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(
                        blank=True, help_text="Reviewer's notes and feedback"
                    ),
                ),
                (
                    "review_decision",
                    models.CharField(
                        blank=True,
                        help_text="Reviewer's decision (e.g., 'resolved', 'requires_action', 'false_positive')",
                        max_length=50,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, help_text="When review was completed", null=True
                    ),
                ),
                (
                    "context_data",
                    models.JSONField(
                        default=dict,
                        help_text="Additional context data for the review (resume_id, user_id, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "due_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this task should be completed",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Human Review Task",
                "verbose_name_plural": "Human Review Tasks",
                "db_table": "human_review_tasks",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MentorApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motivation", models.TextField()),
                ("relevant_experience", models.TextField()),
                (
                    "preferred_payment_method",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe Connect"),
                            ("paypal", "PayPal"),
                            ("bank_transfer", "Bank Transfer"),
                        ],
                        default="stripe",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MentorAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(help_text="Start time (30-minute intervals)"),
                ),
                (
                    "end_time",
                    models.TimeField(help_text="End time (30-minute intervals)"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="MentorNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("session_booking", "Session Booking"),
                            ("session_reminder", "Session Reminder"),
                            ("session_cancellation", "Session Cancellation"),
                            ("payment_received", "Payment Received"),
                            ("review_received", "Review Received"),
                            ("application_update", "Application Update"),
                            ("system_announcement", "System Announcement"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("is_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MentorPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("platform_fee", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "mentor_earnings",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("bank_transfer", "Bank Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("transaction_id", models.CharField(blank=True, max_length=100)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                ("refund_reason", models.TextField(blank=True)),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MentorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primary_track",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("resume_review", "Resume Review"),
                            ("mock_interview", "Mock Interview"),
                            ("career_switch", "Career Switch"),
                            ("advanced_interview", "Advanced Interview"),
                        ],
                        default="",
                        help_text="Primary product track this mentor belongs to",
                        max_length=50,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        help_text="Brief introduction about yourself", max_length=500
                    ),
                ),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(
                        default=0, help_text="Years of professional experience"
                    ),
                ),
                (
                    "current_position",
                    models.CharField(
                        help_text="Current job title and company", max_length=200
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        help_text="Primary industry (e.g., Technology, Finance)",
                        max_length=100,
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        blank=True, help_text="A short headline", max_length=255
                    ),
                ),
                (
                    "starting_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Starting price, pre-filled or auto-updated by Seed script",
                        max_digits=10,
                    ),
                ),
                (
                    "primary_focus",
                    models.CharField(
                        blank=True,
                        help_text="Primary problem this mentor helps with (shown on mentor cards)",
                        max_length=100,
                    ),
                ),
                (
                    "session_focus",
                    models.CharField(
                        blank=True,
                        help_text="One-line session experience summary (shown on mentor cards)",
                        max_length=150,
                    ),
                ),
                (
                    "system_role",
                    models.CharField(
                        blank=True,
                        help_text="System-level role, e.g. Senior System Design Reviewer",
                        max_length=100,
                    ),
                ),
                (
                    "stripe_account_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Connect account ID for payments",
                        max_length=100,
                    ),
                ),
                (
                    "paypal_email",
                    models.EmailField(
                        blank=True,
                        help_text="PayPal email for receiving payments",
                        max_length=254,
                    ),
                ),
                (
                    "bank_account_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Bank account information for wire transfers",
                    ),
                ),
                (
                    "payouts_enabled",
                    models.BooleanField(
                        default=False, help_text="Stripe Connect payouts enabled"
                    ),
                ),
                (
                    "charges_enabled",
                    models.BooleanField(
                        default=False, help_text="Stripe Connect charges enabled"
                    ),
                ),
                (
                    "kyc_disabled_reason",
                    models.CharField(
                        blank=True,
                        help_text="If disabled, Stripe reason",
                        max_length=255,
                    ),
                ),
                (
                    "kyc_due_by",
                    models.DateTimeField(
                        blank=True, help_text="KYC requirements due by", null=True
                    ),
                ),
                (
                    "stripe_capabilities",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stripe capabilities snapshot",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(blank=True, help_text="Admin review notes"),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                (
                    "total_earnings",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total earnings from all sessions",
                        max_digits=10,
                    ),
                ),
                (
                    "total_sessions",
                    models.PositiveIntegerField(
                        default=0, help_text="Total completed sessions"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Mentor verification status"
                    ),
                ),
                (
                    "verification_badge",
                    models.CharField(
                        blank=True, help_text="Verification badge type", max_length=50
                    ),
                ),
                (
                    "specializations",
                    models.JSONField(default=list, help_text="List of specializations"),
                ),
                (
                    "primary_service_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Mentor-selected primary service (SKU anchor)",
                        null=True,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="IANA timezone for availability (e.g., America/New_York)",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MentorReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MentorService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("resume_review", "Resume Review"),
                            ("mock_interview", "Mock Interview"),
                            ("career_consultation", "Career Consultation"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(help_text="Service title", max_length=200)),
                ("description", models.TextField(help_text="Service description")),
                (
                    "deliverables",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of items delivered in this service",
                    ),
                ),
                (
                    "pricing_model",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly Rate"),
                            ("fixed", "Fixed Price"),
                            ("package", "Package Deal"),
                        ],
                        default="hourly",
                        max_length=20,
                    ),
                ),
                (
                    "price_per_hour",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "fixed_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "package_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("package_sessions", models.PositiveIntegerField(default=1)),
                (
                    "platform_fee_percentage",
                    models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
                ),
                (
                    "mentor_earnings_percentage",
                    models.DecimalField(decimal_places=2, default=85.0, max_digits=5),
                ),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["mentor", "service_type"],
            },
        ),
        migrations.CreateModel(
            name="MentorSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(help_text="Scheduled session date"),
                ),
                (
                    "scheduled_time",
                    models.TimeField(help_text="Scheduled session time"),
                ),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Confirmation"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("user_notes", models.TextField(blank=True)),
                ("mentor_notes", models.TextField(blank=True)),
                ("session_feedback", models.TextField(blank=True)),
                ("meeting_link", models.URLField(blank=True)),
                ("meeting_platform", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-scheduled_date", "-scheduled_time"],
            },
        ),
    ]
