# Generated by Django 5.2.4 on 2026-04-16 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ats_signals', '0002_initial'),
        ('human_loop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='humanreviewtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User (mentor/admin) assigned to review this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_review_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='humanreviewtask',
            name='signal',
            field=models.ForeignKey(help_text='ATS Signal that triggered this review task', on_delete=django.db.models.deletion.CASCADE, related_name='review_tasks', to='ats_signals.atssignal'),
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentornotification',
            name='related_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='human_loop.mentorpayment'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorpayment',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='human_loop.mentorprofile'),
        ),
        migrations.AddField(
            model_name='mentornotification',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='human_loop.mentorprofile'),
        ),
        migrations.AddField(
            model_name='mentoravailability',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='human_loop.mentorprofile'),
        ),
        migrations.AddField(
            model_name='mentorreview',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='human_loop.mentorprofile'),
        ),
        migrations.AddField(
            model_name='mentorreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorservice',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='human_loop.mentorprofile'),
        ),
        migrations.AddField(
            model_name='mentorsession',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='human_loop.mentorprofile'),
        ),
        migrations.AddField(
            model_name='mentorsession',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='human_loop.mentorservice'),
        ),
        migrations.AddField(
            model_name='mentorsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorreview',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='human_loop.mentorsession'),
        ),
        migrations.AddField(
            model_name='mentorpayment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_payments', to='human_loop.mentorsession'),
        ),
        migrations.AddField(
            model_name='mentornotification',
            name='related_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='human_loop.mentorsession'),
        ),
        migrations.AddIndex(
            model_name='humanreviewtask',
            index=models.Index(fields=['decision_slot_id'], name='human_revie_decisio_5ac00d_idx'),
        ),
        migrations.AddIndex(
            model_name='humanreviewtask',
            index=models.Index(fields=['status', 'priority'], name='human_revie_status_a045b7_idx'),
        ),
        migrations.AddIndex(
            model_name='humanreviewtask',
            index=models.Index(fields=['assigned_to', 'status'], name='human_revie_assigne_77138d_idx'),
        ),
        migrations.AddIndex(
            model_name='humanreviewtask',
            index=models.Index(fields=['signal', 'status'], name='human_revie_signal__ff573c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mentoravailability',
            unique_together={('mentor', 'day_of_week', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='mentorservice',
            unique_together={('mentor', 'service_type')},
        ),
        migrations.AlterUniqueTogether(
            name='mentorreview',
            unique_together={('mentor', 'user')},
        ),
    ]
