# Generated by Django 5.2.4 on 2026-01-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Admin Capability',
                'verbose_name_plural': 'Admin Capabilities',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='capabilities',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.admincapability'),
        ),
    ]
