# Generated by Django 5.2.4 on 2025-07-30 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('mentors', '0001_initial'),
        ('resumes', '0002_remove_external_api_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('appointment_reminder', 'Appointment Reminder'), ('appointment_confirmed', 'Appointment Confirmed'), ('appointment_cancelled', 'Appointment Cancelled'), ('mentor_response', 'Mentor Response'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('system_announcement', 'System Announcement'), ('resume_analysis_complete', 'Resume Analysis Complete'), ('job_match_found', 'Job Match Found'), ('referral_reward', 'Referral Reward'), ('subscription_expiry', 'Subscription Expiry'), ('welcome', 'Welcome Message')], max_length=50)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification content')),
                ('is_read', models.BooleanField(default=False, help_text='Whether read')),
                ('is_sent', models.BooleanField(default=False, help_text='Whether sent')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, help_text='Sent time', null=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='Read time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointment')),
                ('related_mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mentors.mentorprofile')),
                ('related_resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(choices=[('email', 'Email Template'), ('sms', 'SMS Template'), ('push', 'Push Template'), ('in_app', 'In-App Template')], max_length=20)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=20)),
                ('recipient', models.CharField(help_text='Recipient', max_length=255)),
                ('subject', models.CharField(blank=True, help_text='Subject', max_length=200)),
                ('content', models.TextField(help_text='Delivery content')),
                ('error_message', models.TextField(blank=True, help_text='Error message')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Retry count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notification')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, help_text='Enable email notifications')),
                ('email_appointment_reminders', models.BooleanField(default=True, help_text='Appointment reminder emails')),
                ('email_mentor_responses', models.BooleanField(default=True, help_text='Mentor response emails')),
                ('email_payment_notifications', models.BooleanField(default=True, help_text='Payment notification emails')),
                ('email_system_announcements', models.BooleanField(default=True, help_text='System announcement emails')),
                ('sms_notifications', models.BooleanField(default=False, help_text='Enable SMS notifications')),
                ('sms_appointment_reminders', models.BooleanField(default=False, help_text='Appointment reminder SMS')),
                ('sms_urgent_notifications', models.BooleanField(default=True, help_text='Urgent notification SMS')),
                ('push_notifications', models.BooleanField(default=True, help_text='Enable push notifications')),
                ('push_appointment_reminders', models.BooleanField(default=True, help_text='Appointment reminder push')),
                ('push_mentor_responses', models.BooleanField(default=True, help_text='Mentor response push')),
                ('push_job_matches', models.BooleanField(default=True, help_text='Job match push')),
                ('in_app_notifications', models.BooleanField(default=True, help_text='Enable in-app notifications')),
                ('reminder_advance_hours', models.PositiveIntegerField(default=24, help_text='Appointment reminder advance hours')),
                ('quiet_hours_start', models.TimeField(default='22:00', help_text='Quiet hours start time')),
                ('quiet_hours_end', models.TimeField(default='08:00', help_text='Quiet hours end time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=100)),
                ('template_type', models.CharField(choices=[('email', 'Email Template'), ('sms', 'SMS Template'), ('push', 'Push Template'), ('in_app', 'In-App Template')], max_length=20)),
                ('notification_type', models.CharField(choices=[('appointment_reminder', 'Appointment Reminder'), ('appointment_confirmed', 'Appointment Confirmed'), ('appointment_cancelled', 'Appointment Cancelled'), ('mentor_response', 'Mentor Response'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('system_announcement', 'System Announcement'), ('resume_analysis_complete', 'Resume Analysis Complete'), ('job_match_found', 'Job Match Found'), ('referral_reward', 'Referral Reward'), ('subscription_expiry', 'Subscription Expiry'), ('welcome', 'Welcome Message')], max_length=50)),
                ('subject', models.CharField(blank=True, help_text='Email subject', max_length=200)),
                ('title_template', models.CharField(help_text='Title template', max_length=200)),
                ('message_template', models.TextField(help_text='Message template')),
                ('variables', models.JSONField(default=dict, help_text='Template variables description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['template_type', 'notification_type'],
                'unique_together': {('template_type', 'notification_type')},
            },
        ),
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Batch task name', max_length=100)),
                ('notification_type', models.CharField(choices=[('appointment_reminder', 'Appointment Reminder'), ('appointment_confirmed', 'Appointment Confirmed'), ('appointment_cancelled', 'Appointment Cancelled'), ('mentor_response', 'Mentor Response'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('system_announcement', 'System Announcement'), ('resume_analysis_complete', 'Resume Analysis Complete'), ('job_match_found', 'Job Match Found'), ('referral_reward', 'Referral Reward'), ('subscription_expiry', 'Subscription Expiry'), ('welcome', 'Welcome Message')], max_length=50)),
                ('target_users', models.JSONField(default=list, help_text='Target user ID list')),
                ('target_criteria', models.JSONField(default=dict, help_text='Target user filter criteria')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_count', models.PositiveIntegerField(default=0, help_text='Total count')),
                ('sent_count', models.PositiveIntegerField(default=0, help_text='Sent count')),
                ('failed_count', models.PositiveIntegerField(default=0, help_text='Failed count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'created_at'], name='notificatio_notific_f2e0f7_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority', 'created_at'], name='notificatio_priorit_f7c359_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['delivery_method', 'delivery_status'], name='notificatio_deliver_a0911d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['created_at'], name='notificatio_created_01830a_idx'),
        ),
    ]
