# Generated by Django 5.2.4 on 2025-12-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='payload',
            field=models.JSONField(blank=True, default=dict, help_text='Action payload for navigation'),
        ),
    ]
