# Generated by Django 5.2.4 on 2025-12-10 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('mentors', '0002_mentorprofile_charges_enabled_and_more'),
        ('notifications', '0001_initial'),
        ('resumes', '0003_datadeletionrequest_dataexportjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_role',
            field=models.CharField(blank=True, choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('staff', 'Staff'), ('mentor', 'Mentor'), ('student', 'Student')], help_text='Role-based target (if user is null, all users with this role see it)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical'), ('urgent', 'Urgent')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Specific user target (if null, targets all users with target_role)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['target_role', 'is_read'], name='notificatio_target__89d911_idx'),
        ),
    ]
