# Generated by Django 5.2.4 on 2025-08-27 16:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Default platform fee percentage if service-specific not set', max_digits=5)),
                ('allow_service_override', models.BooleanField(default=True, help_text='Allow MentorService.platform_fee_percentage to override global setting')),
                ('stripe_connect_enabled', models.BooleanField(default=True, help_text='Use Stripe Connect transfers when mentor has stripe_account_id')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payment Settings',
                'verbose_name_plural': 'Payment Settings',
            },
        ),
    ]
