# Generated by Django 5.2.17 on 2026-09-29 21:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=64)),
                ('max_uses', models.PositiveIntegerField()),
                ('uses', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('uses__lte', models.F('max_uses'))), name='peer_invite_uses_within_max')],
            },
        ),
        migrations.CreateModel(
            name='PreRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=40)),
                ('interview_type', models.CharField(blank=True, choices=[('coding', 'Coding'), ('behavioral', 'Behavioral'), ('system_design', 'System design')], default='', max_length=16)),
                ('direction', models.CharField(blank=True, default='', max_length=24)),
                ('timezone', models.CharField(blank=True, default='', max_length=64)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('week_key', models.DateField(help_text='Date the session window starts, in the ops timezone', unique=True)),
                ('invite_at', models.DateTimeField()),
                ('submission_deadline', models.DateTimeField()),
                ('matching_at', models.DateTimeField()),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('earliest_session_start', models.DateTimeField()),
                ('session_minutes', models.PositiveSmallIntegerField(default=60)),
                ('status', models.CharField(choices=[('open', 'Open'), ('matching', 'Matching'), ('matched', 'Matched'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='open', max_length=16)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('algorithm_version', models.CharField(blank=True, default='', max_length=32)),
                ('input_digest', models.CharField(blank=True, default='', max_length=64)),
                ('invites_enqueued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['week_key'],
                'indexes': [models.Index(fields=['status', 'matching_at'], name='peer_mock_r_status_16c8f0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('window_start__lt', models.F('window_end'))), name='peer_round_window_order'), models.CheckConstraint(condition=models.Q(('submission_deadline__lte', models.F('matching_at'))), name='peer_round_deadline_before_matching'), models.CheckConstraint(condition=models.Q(('matching_at__lte', models.F('earliest_session_start'))), name='peer_round_matching_before_sessions')],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('coding', 'Coding'), ('behavioral', 'Behavioral'), ('system_design', 'System design')], max_length=16)),
                ('direction', models.CharField(blank=True, default='', max_length=24)),
                ('standby_ok', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('withdrawn', 'Withdrawn'), ('matched', 'Matched'), ('unmatched', 'Unmatched'), ('partner_cancelled', 'Partner cancelled'), ('dropped', 'Dropped (did not confirm)')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_registrations', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='peer_mock.round')),
            ],
        ),
        migrations.CreateModel(
            name='PeerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='peer_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('actor_ref', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Pseudonymous id used by the event log', unique=True)),
                ('display_name', models.CharField(max_length=40)),
                ('timezone', models.CharField(max_length=64)),
                ('default_interview_type', models.CharField(blank=True, choices=[('coding', 'Coding'), ('behavioral', 'Behavioral'), ('system_design', 'System design')], default='', max_length=16)),
                ('default_direction', models.CharField(blank=True, default='', max_length=24)),
                ('email_round_invites', models.BooleanField(default=False)),
                ('share_email_with_partner', models.BooleanField(default=False)),
                ('terms_version', models.CharField(max_length=16)),
                ('terms_accepted_at', models.DateTimeField()),
                ('adult_confirmed_at', models.DateTimeField()),
                ('completed_count', models.PositiveIntegerField(default=0)),
                ('no_show_count', models.PositiveIntegerField(default=0)),
                ('late_cancel_count', models.PositiveIntegerField(default=0)),
                ('dispute_count', models.PositiveIntegerField(default=0)),
                ('needs_review', models.BooleanField(default=False)),
                ('email_bouncing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invite_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peer_mock.invitecode')),
                ('suspended_until_round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='peer_mock.round')),
            ],
        ),
        migrations.CreateModel(
            name='PeerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('event_type', models.CharField(max_length=40)),
                ('actor_ref', models.UUIDField(blank=True, null=True)),
                ('actor_kind', models.CharField(choices=[('user', 'User'), ('system', 'System'), ('admin', 'Admin')], default='user', max_length=8)),
                ('round_id', models.BigIntegerField(blank=True, null=True)),
                ('session_id', models.BigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', 'occurred_at'], name='peer_mock_p_event_t_f068c4_idx'), models.Index(fields=['actor_ref', 'occurred_at'], name='peer_mock_p_actor_r_481d41_idx'), models.Index(fields=['round_id', 'event_type'], name='peer_mock_p_round_i_c870ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_utc', models.DateTimeField()),
                ('end_utc', models.DateTimeField()),
                ('local_start', models.CharField(max_length=16)),
                ('local_end', models.CharField(max_length=16)),
                ('tz_name', models.CharField(max_length=64)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='peer_mock.registration')),
            ],
            options={
                'ordering': ['start_utc'],
                'indexes': [models.Index(fields=['registration', 'start_utc'], name='peer_mock_a_registr_828c4b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_utc__lt', models.F('end_utc'))), name='peer_window_order')],
            },
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['round', 'interview_type', 'status'], name='peer_mock_r_round_i_8c50b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('round', 'user'), name='peer_one_registration_per_round'),
        ),
    ]
