# Generated by Django 5.2.4 on 2025-07-28 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=200)),
                ('description', models.TextField(help_text='Template description')),
                ('template_type', models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('creative', 'Creative'), ('minimal', 'Minimal'), ('professional', 'Professional')], max_length=20)),
                ('industry', models.CharField(choices=[('technology', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('marketing', 'Marketing'), ('education', 'Education'), ('general', 'General')], default='general', max_length=20)),
                ('html_template', models.TextField(help_text='HTML template content')),
                ('css_styles', models.TextField(help_text='CSS styles for template')),
                ('is_active', models.BooleanField(default=True, help_text='Whether template is available for use')),
                ('is_premium', models.BooleanField(default=False, help_text='Whether template requires premium subscription')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times template has been used')),
                ('preview_image', models.ImageField(blank=True, help_text='Template preview image', upload_to='resume_templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Resume title/name', max_length=200)),
                ('file', models.FileField(help_text='Resume PDF file', upload_to='resumes/')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('analyzing', 'Analyzing'), ('analyzed', 'Analyzed'), ('failed', 'Analysis Failed')], default='uploaded', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(default='pdf', help_text='File type', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.DecimalField(decimal_places=2, help_text='Overall resume score (0-100)', max_digits=5)),
                ('structure_score', models.DecimalField(decimal_places=2, help_text='Structure and format score', max_digits=5)),
                ('content_score', models.DecimalField(decimal_places=2, help_text='Content quality score', max_digits=5)),
                ('keyword_score', models.DecimalField(decimal_places=2, help_text='Keyword optimization score', max_digits=5)),
                ('ats_score', models.DecimalField(decimal_places=2, help_text='ATS compatibility score', max_digits=5)),
                ('extracted_text', models.TextField(help_text='Extracted text from resume')),
                ('detected_keywords', models.JSONField(default=list, help_text='Detected keywords')),
                ('missing_keywords', models.JSONField(default=list, help_text='Missing important keywords')),
                ('industry_keywords', models.JSONField(default=list, help_text='Industry-specific keywords found')),
                ('technical_skills', models.JSONField(default=list, help_text='Technical skills identified')),
                ('soft_skills', models.JSONField(default=list, help_text='Soft skills identified')),
                ('skill_gaps', models.JSONField(default=list, help_text='Recommended skills to add')),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='Years of experience detected')),
                ('job_titles', models.JSONField(default=list, help_text='Job titles found')),
                ('companies', models.JSONField(default=list, help_text='Companies mentioned')),
                ('education_level', models.CharField(blank=True, help_text='Highest education level', max_length=100)),
                ('institutions', models.JSONField(default=list, help_text='Educational institutions')),
                ('certifications', models.JSONField(default=list, help_text='Certifications found')),
                ('analysis_version', models.CharField(default='1.0', help_text='AI analysis version', max_length=20)),
                ('processing_time', models.DecimalField(decimal_places=2, help_text='Analysis processing time in seconds', max_digits=5)),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='AI confidence in analysis', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='resumes.resume')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Comparison title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Comparison description')),
                ('score_improvement', models.DecimalField(decimal_places=2, help_text='Score improvement percentage', max_digits=5)),
                ('improvement_areas', models.JSONField(default=list, help_text='Areas of improvement')),
                ('maintained_strengths', models.JSONField(default=list, help_text='Strengths that were maintained')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('improved_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improved_comparisons', to='resumes.resume')),
                ('original_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_comparisons', to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_comparisons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(help_text='Overall resume summary')),
                ('strengths', models.JSONField(default=list, help_text='Resume strengths')),
                ('weaknesses', models.JSONField(default=list, help_text='Areas for improvement')),
                ('structure_recommendations', models.JSONField(default=list, help_text='Structure improvement suggestions')),
                ('content_recommendations', models.JSONField(default=list, help_text='Content improvement suggestions')),
                ('keyword_recommendations', models.JSONField(default=list, help_text='Keyword optimization suggestions')),
                ('format_recommendations', models.JSONField(default=list, help_text='Formatting suggestions')),
                ('industry_insights', models.JSONField(default=list, help_text='Industry-specific insights')),
                ('market_trends', models.JSONField(default=list, help_text='Current market trends')),
                ('salary_insights', models.JSONField(default=dict, help_text='Salary and compensation insights')),
                ('priority_actions', models.JSONField(default=list, help_text='High priority actions to take')),
                ('quick_fixes', models.JSONField(default=list, help_text='Quick fixes that can be done immediately')),
                ('long_term_improvements', models.JSONField(default=list, help_text='Long-term improvement suggestions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='resumes.resumeanalysis')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('txt', 'Plain Text'), ('html', 'HTML')], max_length=10)),
                ('file_path', models.CharField(help_text='Path to exported file', max_length=500)),
                ('file_size', models.PositiveIntegerField(help_text='Exported file size in bytes')),
                ('customizations', models.JSONField(default=dict, help_text='Customizations applied during export')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_exports', to=settings.AUTH_USER_MODEL)),
                ('template_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resumes.resumetemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
