# Generated by Django 5.2.4 on 2026-04-16 00:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Appointment title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Appointment description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('scheduled_start', models.DateTimeField(help_text='Scheduled start time')),
                ('scheduled_end', models.DateTimeField(help_text='Scheduled end time')),
                ('actual_start', models.DateTimeField(blank=True, help_text='Actual start time', null=True)),
                ('actual_end', models.DateTimeField(blank=True, help_text='Actual end time', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Appointment price', max_digits=8)),
                ('currency', models.CharField(default='USD', help_text='Currency', max_length=3)),
                ('is_paid', models.BooleanField(default=False, help_text='Whether paid')),
                ('payment_method', models.CharField(blank=True, help_text='Payment method', max_length=50)),
                ('meeting_link', models.URLField(blank=True, help_text='Meeting link')),
                ('meeting_platform', models.CharField(blank=True, help_text='Meeting platform', max_length=50)),
                ('meeting_notes', models.TextField(blank=True, help_text='Meeting notes')),
                ('user_rating', models.PositiveIntegerField(blank=True, help_text='User rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('user_feedback', models.TextField(blank=True, help_text='User feedback')),
                ('mentor_rating', models.PositiveIntegerField(blank=True, help_text='Mentor rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('mentor_feedback', models.TextField(blank=True, help_text='Mentor feedback')),
                ('cancellation_reason', models.TextField(blank=True, help_text='Cancellation reason')),
                ('cancelled_by', models.CharField(blank=True, help_text='Cancelled by (user/mentor/system)', max_length=20)),
                ('cancellation_fee', models.DecimalField(decimal_places=2, default=0, help_text='Cancellation fee', max_digits=8)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, help_text='Refund amount', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_date', models.DateField(help_text='Preferred date')),
                ('preferred_time_start', models.TimeField(help_text='Preferred start time')),
                ('preferred_time_end', models.TimeField(help_text='Preferred end time')),
                ('alternative_dates', models.JSONField(default=list, help_text='Alternative dates')),
                ('title', models.CharField(help_text='Appointment title', max_length=200)),
                ('description', models.TextField(help_text='Appointment description')),
                ('topics', models.JSONField(default=list, help_text='Discussion topics')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('mentor_response', models.TextField(blank=True, help_text='Mentor response')),
                ('suggested_time_slots', models.JSONField(default=list, help_text='Mentor suggested time slots')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='Request expiration time')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='Start time')),
                ('end_time', models.DateTimeField(help_text='End time')),
                ('is_available', models.BooleanField(default=True, help_text='Whether available')),
                ('is_recurring', models.BooleanField(default=False, help_text='Whether recurring time')),
                ('recurring_pattern', models.CharField(blank=True, help_text='Recurring pattern (weekly, monthly)', max_length=50)),
                ('max_bookings', models.PositiveIntegerField(default=1, help_text='Maximum bookings')),
                ('current_bookings', models.PositiveIntegerField(default=0, help_text='Current bookings')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price', max_digits=8)),
                ('currency', models.CharField(default='USD', help_text='Currency', max_length=3)),
                ('reserved_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
