# Generated by Django 5.2.4 on 2026-01-05 04:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('human_loop', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Appointment title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Appointment description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('scheduled_start', models.DateTimeField(help_text='Scheduled start time')),
                ('scheduled_end', models.DateTimeField(help_text='Scheduled end time')),
                ('actual_start', models.DateTimeField(blank=True, help_text='Actual start time', null=True)),
                ('actual_end', models.DateTimeField(blank=True, help_text='Actual end time', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Appointment price', max_digits=8)),
                ('currency', models.CharField(default='USD', help_text='Currency', max_length=3)),
                ('is_paid', models.BooleanField(default=False, help_text='Whether paid')),
                ('payment_method', models.CharField(blank=True, help_text='Payment method', max_length=50)),
                ('meeting_link', models.URLField(blank=True, help_text='Meeting link')),
                ('meeting_platform', models.CharField(blank=True, help_text='Meeting platform', max_length=50)),
                ('meeting_notes', models.TextField(blank=True, help_text='Meeting notes')),
                ('user_rating', models.PositiveIntegerField(blank=True, help_text='User rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('user_feedback', models.TextField(blank=True, help_text='User feedback')),
                ('mentor_rating', models.PositiveIntegerField(blank=True, help_text='Mentor rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('mentor_feedback', models.TextField(blank=True, help_text='Mentor feedback')),
                ('cancellation_reason', models.TextField(blank=True, help_text='Cancellation reason')),
                ('cancelled_by', models.CharField(blank=True, help_text='Cancelled by (user/mentor/system)', max_length=20)),
                ('cancellation_fee', models.DecimalField(decimal_places=2, default=0, help_text='Cancellation fee', max_digits=8)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, help_text='Refund amount', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='human_loop.mentorprofile')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='human_loop.mentorservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'decision_slots_appointment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_date', models.DateField(help_text='Preferred date')),
                ('preferred_time_start', models.TimeField(help_text='Preferred start time')),
                ('preferred_time_end', models.TimeField(help_text='Preferred end time')),
                ('alternative_dates', models.JSONField(default=list, help_text='Alternative dates')),
                ('title', models.CharField(help_text='Appointment title', max_length=200)),
                ('description', models.TextField(help_text='Appointment description')),
                ('topics', models.JSONField(default=list, help_text='Discussion topics')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('mentor_response', models.TextField(blank=True, help_text='Mentor response')),
                ('suggested_time_slots', models.JSONField(default=list, help_text='Mentor suggested time slots')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='Request expiration time')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_requests', to='human_loop.mentorprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'decision_slots_appointmentrequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='Start time')),
                ('end_time', models.DateTimeField(help_text='End time')),
                ('is_available', models.BooleanField(default=True, help_text='Whether available')),
                ('is_recurring', models.BooleanField(default=False, help_text='Whether recurring time')),
                ('recurring_pattern', models.CharField(blank=True, help_text='Recurring pattern (weekly, monthly)', max_length=50)),
                ('max_bookings', models.PositiveIntegerField(default=1, help_text='Maximum bookings')),
                ('current_bookings', models.PositiveIntegerField(default=0, help_text='Current bookings')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price', max_digits=8)),
                ('currency', models.CharField(default='USD', help_text='Currency', max_length=3)),
                ('reserved_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='human_loop.mentorprofile')),
                ('reserved_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_slot', to='appointments.appointment')),
            ],
            options={
                'db_table': 'decision_slots_timeslot',
                'ordering': ['start_time'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.timeslot'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['mentor', 'start_time'], name='decision_sl_mentor__ddbab5_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['is_available', 'start_time'], name='decision_sl_is_avai_518fa3_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['user', 'status'], name='decision_sl_user_id_462c00_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['mentor', 'status'], name='decision_sl_mentor__cfcbc7_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['scheduled_start'], name='decision_sl_schedul_2a65c4_idx'),
        ),
    ]
