# Generated by Django 5.2.4 on 2026-04-16 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_initial'),
        ('human_loop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_requests', to='human_loop.mentorprofile'),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='human_loop.mentorprofile'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='reserved_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_slot', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.timeslot'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['mentor', 'start_time'], name='appointment_mentor__2114be_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['is_available', 'start_time'], name='appointment_is_avai_82905c_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['user', 'status'], name='appointment_user_id_4f7212_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['mentor', 'status'], name='appointment_mentor__ce95fc_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['scheduled_start'], name='appointment_schedul_d6575a_idx'),
        ),
    ]
