# Generated by Django 5.2.4 on 2026-04-16 00:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusPowerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(choices=[('KERNEL_CORE_BUS', 'Kernel Core Bus'), ('PUBLIC_WEB_BUS', 'Public Web Bus'), ('ADMIN_BUS', 'Admin Bus'), ('AI_BUS', 'AI Capability Bus'), ('PEER_MOCK_BUS', 'Peer Mock Runtime Bus'), ('MENTOR_BUS', 'Mentor / Human-Loop Bus'), ('PAYMENT_BUS', 'Payment / Transaction Bus'), ('SEARCH_BUS', 'Search / Discovery Bus')], help_text='Canonical bus identifier', max_length=50, unique=True)),
                ('state', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', help_text='ON = requests pass through; OFF = immediate 404', max_length=3)),
                ('reason', models.TextField(blank=True, help_text='Why this bus is in its current state')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bus Power State',
                'verbose_name_plural': 'Bus Power States',
                'ordering': ['bus_name'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, help_text='Unique feature key (e.g., PEER_MOCK, MENTORS, PAYMENTS)', max_length=100, unique=True)),
                ('state', models.CharField(choices=[('OFF', 'Disabled (404)'), ('BETA', 'Beta (SuperAdmin Only)'), ('ON', 'Enabled')], default='OFF', help_text='Current state of this feature', max_length=10)),
                ('visibility', models.CharField(choices=[('internal', 'Internal Only'), ('staff', 'Staff Access'), ('user', 'User Access'), ('public', 'Public Access')], default='internal', help_text='Who can see this feature', max_length=20)),
                ('rollout_rule', models.JSONField(blank=True, default=dict, help_text='Rollout rules (e.g., percentage, user whitelist)')),
                ('reason', models.TextField(blank=True, help_text='Reason for current state')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='GovernanceAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('PLATFORM_STATE_UPDATE', 'Platform State Updated'), ('FEATURE_FLAG_CREATE', 'Feature Flag Created'), ('FEATURE_FLAG_UPDATE', 'Feature Flag Updated'), ('GOVERNANCE_INIT', 'Governance Initialized'), ('WORKLOAD_ACTIVATE', 'Workload Activated'), ('WORKLOAD_FREEZE', 'Workload Frozen'), ('MODULE_ENABLE', 'Module Enabled'), ('MODULE_DISABLE', 'Module Disabled')], help_text='Type of governance action performed', max_length=50)),
                ('payload', models.JSONField(default=dict, help_text='Details of the change (before/after state, affected keys, etc.)')),
                ('reason', models.TextField(help_text='Reason for this action (required for all changes)')),
                ('world', models.CharField(blank=True, default='kernel', help_text='OS world: public, app, admin, or kernel', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Governance Audit',
                'verbose_name_plural': 'Governance Audit Log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KernelArbitrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.CharField(db_index=True, help_text='Resource ID from sys_claim', max_length=255)),
                ('bucket_start', models.DateTimeField(db_index=True, help_text='Start of 2-second arbitration bucket')),
                ('winner_hash', models.CharField(blank=True, default='', help_text='SHA256 hash of winner', max_length=64)),
                ('winner_owner_id', models.CharField(blank=True, default='', help_text='Owner ID of winner', max_length=128)),
                ('winner_context_hash', models.CharField(blank=True, default='', help_text='Context hash of winner', max_length=128)),
                ('decided_at', models.DateTimeField(blank=True, help_text='When winner was decided', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KernelAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(max_length=128)),
                ('decision_id', models.CharField(max_length=128)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128)),
                ('context_hash', models.CharField(max_length=128)),
                ('schema_version', models.CharField(default='1.0', max_length=10)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('EMITTED', 'Emitted'), ('HANDLED', 'Handled'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected')], db_index=True, default='EMITTED', max_length=16)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, db_index=True, help_text='EMITTED->HANDLED latency in milliseconds', null=True)),
                ('congestion_flag', models.BooleanField(db_index=True, default=False, help_text='Set if latency > 5000ms')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KernelIdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('event_type', models.CharField(blank=True, db_index=True, max_length=128)),
                ('decision_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('context_hash', models.CharField(blank=True, max_length=64)),
                ('owner_id', models.CharField(blank=True, help_text='Owner ID for semantic collision detection', max_length=128)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUCCEEDED', 'Succeeded'), ('PROCESSED', 'Processed'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], db_index=True, default='IN_PROGRESS', max_length=16)),
                ('processed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_event_id', models.UUIDField(blank=True, help_text='Pointer to KernelAuditLog', null=True)),
                ('failure_reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('SINGLE_WORKLOAD', 'Single Workload Mode'), ('MULTI_WORKLOAD', 'Multi Workload Mode'), ('MAINTENANCE', 'Maintenance Mode'), ('MIGRATION', 'Migration Mode')], default='SINGLE_WORKLOAD', help_text='Current platform operating state', max_length=50)),
                ('active_workloads', models.JSONField(default=list, help_text='List of currently active workload identifiers (e.g., ["PEER_MOCK"])')),
                ('frozen_modules', models.JSONField(default=list, help_text='List of frozen module identifiers that return 404')),
                ('governance_version', models.PositiveIntegerField(default=1, help_text='Incremented on every change to invalidate middleware cache')),
                ('reason', models.TextField(help_text='Reason for the current state configuration')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Platform State',
                'verbose_name_plural': 'Platform State',
                'ordering': ['-updated_at'],
            },
        ),
    ]
