# Generated by Django 5.2.4 on 2026-01-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KernelIdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=128)),
                ('decision_id', models.CharField(db_index=True, max_length=128)),
                ('context_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PROCESSED', 'Processed'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], db_index=True, default='PROCESSED', max_length=16)),
                ('processed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_event_id', models.UUIDField(blank=True, help_text='Pointer to KernelAuditLog', null=True)),
                ('failure_reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='kernelauditlog',
            new_name='kernel_kern_event_t_c3ed85_idx',
            old_name='kernel_kern_event_t_535ea0_idx',
        ),
        migrations.RenameIndex(
            model_name='kernelauditlog',
            new_name='kernel_kern_decisio_c9a7ac_idx',
            old_name='kernel_kern_decisio_03dd8e_idx',
        ),
        migrations.AddField(
            model_name='kernelauditlog',
            name='congestion_flag',
            field=models.BooleanField(db_index=True, default=False, help_text='Set if latency > 5000ms'),
        ),
        migrations.AddField(
            model_name='kernelauditlog',
            name='handled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='kernelauditlog',
            name='latency_ms',
            field=models.IntegerField(blank=True, db_index=True, help_text='EMITTED->HANDLED latency in milliseconds', null=True),
        ),
        migrations.AlterField(
            model_name='kernelauditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='kernelauditlog',
            index=models.Index(fields=['status', 'created_at'], name='kernel_kern_status_27ad55_idx'),
        ),
        migrations.AddIndex(
            model_name='kernelauditlog',
            index=models.Index(fields=['congestion_flag', 'created_at'], name='kernel_kern_congest_d7d529_idx'),
        ),
        migrations.AddIndex(
            model_name='kernelidempotencyrecord',
            index=models.Index(fields=['event_type', 'processed_at'], name='kernel_kern_event_t_cf78ef_idx'),
        ),
        migrations.AddIndex(
            model_name='kernelidempotencyrecord',
            index=models.Index(fields=['decision_id', 'processed_at'], name='kernel_kern_decisio_8f0a08_idx'),
        ),
        migrations.AddIndex(
            model_name='kernelidempotencyrecord',
            index=models.Index(fields=['status', 'processed_at'], name='kernel_kern_status_8acb51_idx'),
        ),
    ]
