# Generated by Django 5.2.4 on 2026-04-16 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kernel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='buspowerstate',
            name='updated_by',
            field=models.ForeignKey(help_text='SuperAdmin who last changed this bus', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus_power_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='updated_by',
            field=models.ForeignKey(help_text='SuperAdmin who last updated this flag', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_flag_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='governanceaudit',
            name='actor',
            field=models.ForeignKey(help_text='User who performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governance_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='kernelarbitrationrecord',
            index=models.Index(fields=['resource_id', 'bucket_start'], name='kernel_kern_resourc_f16bda_idx'),
        ),
        migrations.AddIndex(
            model_name='kernelarbitrationrecord',
            index=models.Index(fields=['decided_at'], name='kernel_kern_decided_3f1d43_idx'),
        ),
        migrations.AddConstraint(
            model_name='kernelarbitrationrecord',
            constraint=models.UniqueConstraint(fields=('resource_id', 'bucket_start'), name='uniq_arb_resource_bucket'),
        ),
        migrations.AddIndex(
            model_name='kernelauditlog',
            index=models.Index(fields=['event_type', 'created_at'], name='kernel_kern_event_t_c3ed85_idx'),
        ),
        migrations.AddIndex(
            model_name='kernelauditlog',
            index=models.Index(fields=['decision_id', 'created_at'], name='kernel_kern_decisio_c9a7ac_idx'),
        ),
        migrations.AddIndex(
            model_name='kernelauditlog',
            index=models.Index(fields=['status', 'created_at'], name='kernel_kern_status_27ad55_idx'),
        ),
        migrations.AddIndex(
            model_name='kernelauditlog',
            index=models.Index(fields=['congestion_flag', 'created_at'], name='kernel_kern_congest_d7d529_idx'),
        ),
        migrations.AddIndex(
            model_name='kernelidempotencyrecord',
            index=models.Index(fields=['event_type', 'processed_at'], name='kernel_kern_event_t_cf78ef_idx'),
        ),
        migrations.AddIndex(
            model_name='kernelidempotencyrecord',
            index=models.Index(fields=['decision_id', 'processed_at'], name='kernel_kern_decisio_8f0a08_idx'),
        ),
        migrations.AddIndex(
            model_name='kernelidempotencyrecord',
            index=models.Index(fields=['status', 'processed_at'], name='kernel_kern_status_8acb51_idx'),
        ),
        migrations.AddField(
            model_name='platformstate',
            name='updated_by',
            field=models.ForeignKey(help_text='SuperAdmin who last updated this state', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_state_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
