# Generated by Django 5.2.4 on 2026-09-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governanceaudit',
            name='action',
            field=models.CharField(choices=[('PLATFORM_STATE_UPDATE', 'Platform State Updated'), ('FEATURE_FLAG_CREATE', 'Feature Flag Created'), ('FEATURE_FLAG_UPDATE', 'Feature Flag Updated'), ('GOVERNANCE_INIT', 'Governance Initialized'), ('WORKLOAD_ACTIVATE', 'Workload Activated'), ('WORKLOAD_FREEZE', 'Workload Frozen'), ('MODULE_ENABLE', 'Module Enabled'), ('MODULE_DISABLE', 'Module Disabled'), ('BUS_ENABLE', 'Bus Powered On'), ('BUS_DISABLE', 'Bus Powered Off')], help_text='Type of governance action performed', max_length=50),
        ),
    ]
