# Generated by Django 5.2.4 on 2026-09-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0003_add_bus_audit_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buspowerstate',
            name='bus_name',
            field=models.CharField(choices=[('KERNEL_CORE_BUS', 'Kernel Core Bus'), ('PUBLIC_WEB_BUS', 'Public Web Bus'), ('ADMIN_BUS', 'Admin Bus'), ('AI_BUS', 'AI Capability Bus'), ('PEER_MOCK_BUS', 'Peer Mock Runtime Bus'), ('MENTOR_BUS', 'Mentor / Human-Loop Bus'), ('PAYMENT_BUS', 'Payment / Transaction Bus'), ('SEARCH_BUS', 'Search / Discovery Bus'), ('CHAT_BUS', 'Chat Bus')], help_text='Canonical bus identifier', max_length=50, unique=True),
        ),
    ]
