# Generated by Django 5.2.4 on 2026-01-13 20:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0005_add_owner_id_to_idempotency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, help_text='Unique feature key (e.g., PEER_MOCK, MENTORS, PAYMENTS)', max_length=100, unique=True)),
                ('state', models.CharField(choices=[('OFF', 'Disabled (404)'), ('BETA', 'Beta (SuperAdmin Only)'), ('ON', 'Enabled')], default='OFF', help_text='Current state of this feature', max_length=10)),
                ('visibility', models.CharField(choices=[('internal', 'Internal Only'), ('staff', 'Staff Access'), ('user', 'User Access'), ('public', 'Public Access')], default='internal', help_text='Who can see this feature', max_length=20)),
                ('rollout_rule', models.JSONField(blank=True, default=dict, help_text='Rollout rules (e.g., percentage, user whitelist)')),
                ('reason', models.TextField(blank=True, help_text='Reason for current state')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='GovernanceAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('PLATFORM_STATE_UPDATE', 'Platform State Updated'), ('FEATURE_FLAG_CREATE', 'Feature Flag Created'), ('FEATURE_FLAG_UPDATE', 'Feature Flag Updated'), ('GOVERNANCE_INIT', 'Governance Initialized'), ('WORKLOAD_ACTIVATE', 'Workload Activated'), ('WORKLOAD_FREEZE', 'Workload Frozen'), ('MODULE_ENABLE', 'Module Enabled'), ('MODULE_DISABLE', 'Module Disabled')], help_text='Type of governance action performed', max_length=50)),
                ('payload', models.JSONField(default=dict, help_text='Details of the change (before/after state, affected keys, etc.)')),
                ('reason', models.TextField(help_text='Reason for this action (required for all changes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Governance Audit',
                'verbose_name_plural': 'Governance Audit Log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('SINGLE_WORKLOAD', 'Single Workload Mode'), ('MULTI_WORKLOAD', 'Multi Workload Mode'), ('MAINTENANCE', 'Maintenance Mode'), ('MIGRATION', 'Migration Mode')], default='SINGLE_WORKLOAD', help_text='Current platform operating state', max_length=50)),
                ('active_workloads', models.JSONField(default=list, help_text='List of currently active workload identifiers (e.g., ["PEER_MOCK"])')),
                ('frozen_modules', models.JSONField(default=list, help_text='List of frozen module identifiers that return 404')),
                ('governance_version', models.PositiveIntegerField(default=1, help_text='Incremented on every change to invalidate middleware cache')),
                ('reason', models.TextField(help_text='Reason for the current state configuration')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Platform State',
                'verbose_name_plural': 'Platform State',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='featureflag',
            name='updated_by',
            field=models.ForeignKey(help_text='SuperAdmin who last updated this flag', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_flag_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='governanceaudit',
            name='actor',
            field=models.ForeignKey(help_text='User who performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governance_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='platformstate',
            name='updated_by',
            field=models.ForeignKey(help_text='SuperAdmin who last updated this state', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_state_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
