# Generated by Django 5.2.4 on 2026-01-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0006_add_governance_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='governanceaudit',
            name='world',
            field=models.CharField(blank=True, default='kernel', help_text='OS world: public, app, admin, or kernel', max_length=20),
        ),
    ]
