# Generated by Django 5.2.4 on 2026-03-21 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kernel", "0007_add_world_to_governance_audit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusPowerState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bus_name",
                    models.CharField(
                        choices=[
                            ("KERNEL_CORE_BUS", "Kernel Core Bus"),
                            ("PUBLIC_WEB_BUS", "Public Web Bus"),
                            ("ADMIN_BUS", "Admin Bus"),
                            ("AI_BUS", "AI Capability Bus"),
                            ("PEER_MOCK_BUS", "Peer Mock Runtime Bus"),
                            ("MENTOR_BUS", "Mentor / Human-Loop Bus"),
                            ("PAYMENT_BUS", "Payment / Transaction Bus"),
                            ("SEARCH_BUS", "Search / Discovery Bus"),
                        ],
                        help_text="Canonical bus identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("ON", "ON"), ("OFF", "OFF")],
                        default="OFF",
                        help_text="ON = requests pass through; OFF = immediate 404",
                        max_length=3,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Why this bus is in its current state"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Bus Power State",
                "verbose_name_plural": "Bus Power States",
                "ordering": ["bus_name"],
            },
        ),
        migrations.AddField(
            model_name="buspowerstate",
            name="updated_by",
            field=models.ForeignKey(
                help_text="SuperAdmin who last changed this bus",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bus_power_updates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
