# Generated by Django 5.2.4 on 2025-07-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
