# Generated by Django 5.2.4 on 2025-12-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_password_reset_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('mentor', 'Mentor'), ('student', 'Student'), ('staff', 'Staff')], default='student', max_length=10),
        ),
    ]
