# Generated by Django 5.2.4 on 2025-12-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('mentor', 'Mentor'), ('student', 'Student'), ('staff', 'Staff')], default='student', max_length=10),
        ),
    ]
